In [1]:
#!pip install pmlb
import pandas as pd
import numpy as np
from pmlb import fetch_data

In [2]:
# dataset for this demo
#https://github.com/EpistasisLab/penn-ml-benchmarks/tree/master/datasets/classification/GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1
gametes = fetch_data('GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1')
print(gametes.describe())

                N0           N1           N2           N3           N4  \
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean      0.020625     0.261250     0.728750     0.889375     0.354375
std       0.142170     0.475015     0.673949     0.702635     0.523416
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     1.000000     1.000000     0.000000
75%       0.000000     0.000000     1.000000     1.000000     1.000000
max       1.000000     2.000000     2.000000     2.000000     2.000000

                N5           N6           N7           N8           N9  ...  \
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000  ...
mean      0.791250     0.502500     0.728750     0.346875     0.761875  ...
std       0.695864     0.615614     0.684994     0.540125     0.694062  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
50%       1.000000     0.000000     1.000000     0.000000     1.000000  ...
75%       1.000000     1.000000     1.000000     1.000000     1.000000  ...
max       2.000000     2.000000     2.000000     2.000000     2.000000  ...

               N11          N12          N13          N14          N15  \
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean      0.860000     0.478125     0.076250     0.178125     0.666250
std       0.712894     0.606012     0.270151     0.398743     0.657747
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       1.000000     0.000000     0.000000     0.000000     1.000000
75%       1.000000     1.000000     0.000000     0.000000     1.000000
max       2.000000     2.000000     2.000000     2.000000     2.000000

               N16          N17           P1           P2       target
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean      0.425625     0.778750     0.406250     0.404375     0.500000
std       0.576347     0.703639     0.578939     0.562186     0.500156
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     1.000000     0.000000     0.000000     0.500000
75%       1.000000     1.000000     1.000000     1.000000     1.000000
max       2.000000     2.000000     2.000000     2.000000     1.000000

[8 rows x 21 columns]

In [3]:
gametes.head()

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,P1,P2,target
0,0,0,2,1,1,0,0,2,0,1,...,2,1,0,0,0,0,0,0,1,1
1,0,0,1,0,0,1,1,0,0,1,...,0,1,0,0,0,0,0,0,0,1
2,0,0,0,1,0,2,0,0,0,0,...,1,1,0,0,2,2,0,0,0,1
3,0,1,0,2,0,1,0,2,0,0,...,1,1,0,1,1,0,1,1,0,1
4,0,0,1,1,0,0,0,1,1,0,...,1,0,0,1,0,0,1,1,0,1

In [4]:
X=gametes.drop('target',axis=1)

# features for A
A_feat_list = [
                'N10',
                'N11',
                'N12'
                ]

# features for C
C_feat_list = [
                'N13',
                'N14',
                'N15'
                ]
# y

y = gametes['target']

In [5]:
# test metaestimator alone
from tpot.builtins import MetaEstimator
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
metaest = MetaEstimator(estimator=GradientBoostingRegressor(random_state=42), A=A_feat_list, C=C_feat_list)
metaest.fit(X_train, y_train)
metaest.values_list

['ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary',
 'ternary']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train.head()

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,P1,P2
820,0,0,0,2,1,1,0,1,1,0,0,1,1,1,0,0,1,1,1,1
567,0,0,0,0,0,0,0,0,0,0,0,2,2,0,1,0,0,2,0,1
355,0,1,0,1,1,1,1,1,0,1,0,1,2,0,0,0,1,0,0,0
1545,0,0,0,2,1,0,0,1,1,2,0,0,0,0,0,1,2,1,1,1
209,0,0,1,2,1,2,2,0,0,0,0,1,1,1,0,0,0,2,0,1

In [7]:
y_pred = metaest.predict(X_train)

In [8]:
from tpot.metrics import balanced_accuracy
b_acc = balanced_accuracy(y_true=y_train, y_pred=y_pred)
print(b_acc)

0.7294635022771905

In [9]:
print(metaest.score(X_test, y_test))

0.5492424242424242

In [10]:
# metaestimator is passed when using it as a stand-alone estimator

In [11]:
# test metaestimator with cross_eval_score
cv_scores = cross_val_score(metaest, X, y, cv=3)
print(cv_scores)

[0.53370787 0.70731707 0.65290807]

In [12]:
# test MetaClassifier for binary output
from tpot.builtins import MetaClassifier
metaest2 = MetaClassifier(estimator=GradientBoostingRegressor(random_state=42), A=A_feat_list, C=C_feat_list)

cv_scores = cross_val_score(metaest2, X, y, cv=3, error_score="raise")
print(cv_scores)

[0.53370787 0.70731707 0.65290807]

In [13]:
# score is matched

In [14]:
# make a 3-class classification
y_012 = y
y_1_index = np.where(y_012 == 1)

# make 1st 1/3 of class 1 to class 2
size_2 = int(y_1_index[0].size/3)
y_012[y_1_index[0][:size_2]] = 2

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y_012, test_size=0.33, random_state=42)
X_train.head()

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,P1,P2
820,0,0,0,2,1,1,0,1,1,0,0,1,1,1,0,0,1,1,1,1
567,0,0,0,0,0,0,0,0,0,0,0,2,2,0,1,0,0,2,0,1
355,0,1,0,1,1,1,1,1,0,1,0,1,2,0,0,0,1,0,0,0
1545,0,0,0,2,1,0,0,1,1,2,0,0,0,0,0,1,2,1,1,1
209,0,0,1,2,1,2,2,0,0,0,0,1,1,1,0,0,0,2,0,1

In [16]:
# Test metaestimator with TPOT with config

from tpot import TPOTClassifier


tpot_config = {
    'tpot.builtins.FeatureSetSelector': {
        'subset_list': ['./subset_test.csv'],
        'sel_subset': [0, 1],
        'res_cols': [['N10', 'N11', 'N12', 'N13', 'N14', 'N15']]
    },
   'tpot.builtins.MetaClassifier': {
        
        'estimator': {
           'sklearn.ensemble.GradientBoostingRegressor': {
                'n_estimators': [100],
                'loss': ["ls", "lad", "huber", "quantile"],
                'learning_rate': [1e-3, 1e-2, 1e-1, 0.5, 1.],
                'max_depth': range(1, 11),
                'min_samples_split': range(2, 21),
                'min_samples_leaf': range(1, 21),
                'subsample': np.arange(0.05, 1.01, 0.05),
                'max_features': np.arange(0.05, 1.01, 0.05),
                'alpha': [0.75, 0.8, 0.85, 0.9, 0.95, 0.99]
            },

        },
       'A': [A_feat_list],
       'C': [C_feat_list]
    }
    
}


tpot = TPOTClassifier(generations=5, population_size=25, 
                        verbosity=3, cv=5,
                      config_dict=tpot_config,
                      template="FeatureSetSelector-Classifier",
                      scoring="balanced_accuracy",random_state=42)
tpot.fit(X_train, y_train)

2 operators have been imported by TPOT.

HBox(children=(FloatProgress(value=0.0, description='Optimization Progress', max=150.0, style=ProgressStyle(deâ€¦

Generation 1 - Current Pareto front scores:
-2	0.6610605324638996	MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.75, MetaClassifier__GradientBoostingRegressor__learning_rate=0.1, MetaClassifier__GradientBoostingRegressor__loss=lad, MetaClassifier__GradientBoostingRegressor__max_depth=7, MetaClassifier__GradientBoostingRegressor__max_features=1.0, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=3, MetaClassifier__GradientBoostingRegressor__min_samples_split=19, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=1.0)

Generation 2 - Current Pareto front scores:
-2	0.6617440751821267	MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.75, MetaClassifier__GradientBoostingRegressor__learning_rate=0.1, MetaClassifier__GradientBoostingRegressor__loss=lad, MetaClassifier__GradientBoostingRegressor__max_depth=10, MetaClassifier__GradientBoostingRegressor__max_features=1.0, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=3, MetaClassifier__GradientBoostingRegressor__min_samples_split=19, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=1.0)

Generation 3 - Current Pareto front scores:
-2	0.6617440751821267	MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.75, MetaClassifier__GradientBoostingRegressor__learning_rate=0.1, MetaClassifier__GradientBoostingRegressor__loss=lad, MetaClassifier__GradientBoostingRegressor__max_depth=10, MetaClassifier__GradientBoostingRegressor__max_features=1.0, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=3, MetaClassifier__GradientBoostingRegressor__min_samples_split=19, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=1.0)

Pipeline encountered that has previously been evaluated during the optimization process. Using the score from the previous evaluation.
Generation 4 - Current Pareto front scores:
-2	0.6625302373209865	MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.75, MetaClassifier__GradientBoostingRegressor__learning_rate=0.1, MetaClassifier__GradientBoostingRegressor__loss=lad, MetaClassifier__GradientBoostingRegressor__max_depth=7, MetaClassifier__GradientBoostingRegressor__max_features=0.9500000000000001, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=3, MetaClassifier__GradientBoostingRegressor__min_samples_split=10, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=1.0)

Generation 5 - Current Pareto front scores:
-2	0.6628019231505979	MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.75, MetaClassifier__GradientBoostingRegressor__learning_rate=0.1, MetaClassifier__GradientBoostingRegressor__loss=lad, MetaClassifier__GradientBoostingRegressor__max_depth=10, MetaClassifier__GradientBoostingRegressor__max_features=0.9000000000000001, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=3, MetaClassifier__GradientBoostingRegressor__min_samples_split=19, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=1.0)

TPOTClassifier(config_dict={'tpot.builtins.FeatureSetSelector': {'res_cols': [['N10',
                                                                               'N11',
                                                                               'N12',
                                                                               'N13',
                                                                               'N14',
                                                                               'N15']],
                                                                 'sel_subset': [0,
                                                                                1],
                                                                 'subset_list': ['./subset_test.csv']},
                            'tpot.builtins.MetaClassifier': {'A': [['N10',
                                                                    'N11',
                                                                    'N12']],
                                                             'C': [['N13',
                                                                    'N14',
                                                                    'N15']],
                                                             'estimator': {'sklearn.ensemble.GradientBoostingRegressor': {'alpha': [0.75,
                                                                                                                                    0.8,
                                                                                                                                    0.85,
                                                                                                                                    0.9,
                                                                                                                                    0.95,
                                                                                                                                    0.99...
               crossover_rate=0.1, cv=5, disable_update_check=False,
               early_stop=None, generations=5, max_eval_time_mins=5,
               max_time_mins=None, memory=None, mutation_rate=0.9, n_jobs=1,
               offspring_size=None, periodic_checkpoint_folder=None,
               population_size=25, random_state=42, scoring='balanced_accuracy',
               subsample=1.0, template='FeatureSetSelector-Classifier',
               use_dask=False, verbosity=3, warm_start=False)

In [17]:
list(tpot.evaluated_individuals_.keys())[0]

"MetaClassifier(FeatureSetSelector(input_matrix, FeatureSetSelector__res_cols=['N10', 'N11', 'N12', 'N13', 'N14', 'N15'], FeatureSetSelector__sel_subset=0, FeatureSetSelector__subset_list=./subset_test.csv), MetaClassifier__A=['N10', 'N11', 'N12'], MetaClassifier__C=['N13', 'N14', 'N15'], MetaClassifier__GradientBoostingRegressor__alpha=0.9, MetaClassifier__GradientBoostingRegressor__learning_rate=1.0, MetaClassifier__GradientBoostingRegressor__loss=huber, MetaClassifier__GradientBoostingRegressor__max_depth=8, MetaClassifier__GradientBoostingRegressor__max_features=0.35000000000000003, MetaClassifier__GradientBoostingRegressor__min_samples_leaf=19, MetaClassifier__GradientBoostingRegressor__min_samples_split=12, MetaClassifier__GradientBoostingRegressor__n_estimators=100, MetaClassifier__GradientBoostingRegressor__subsample=0.55)"

In [18]:
print(tpot.score(X_test, y_test))

0.6372113933969797