In [1]:
import pandas as pd
import numpy as np
import sys
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from tpot.config import classifier_config_dict

In [2]:
Xdata = pd.read_csv('testingData/data.txt', sep='\t', index_col='id')
Ydata = Xdata['population']
Xdata.drop(['population'], axis=1,  inplace=True)

In [3]:
Xdata.head()

,lab1,lab2,lab3,lab4,lab5,lab6,hsa-let-7a-1-3p,hsa-let-7a-1-5p,hsa-let-7a-2-3p,hsa-let-7a-2-5p,...,hsa-miR-95-3p,hsa-miR-95-5p,hsa-miR-96-3p,hsa-miR-96-5p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
id,,,,,,,,,,,,,,,,,,,,,
HG00096.1.MI_120104_4,1,0,0,0,0,0,29.179331,31957.203647,0.0,31957.203647,...,0.000000,0.0,0.0,1.945289,7.781155,2989.908815,1.945289,47.659574,3.890578,145.896657
HG00097.7.MI_120224_2,0,0,0,0,0,0,52.115453,48432.193453,0.0,48432.193453,...,0.000000,0.0,0.0,2.605773,26.057727,4737.294687,0.000000,35.177931,0.000000,53.418339
HG00099.5.MI_120327_3,0,0,0,0,1,0,38.016573,46152.599004,0.0,46152.599004,...,0.159734,0.0,0.0,0.159734,5.910140,4121.603517,1.437602,70.282740,1.277868,87.693692
HG00100.2.MI_120126_4,0,1,0,0,0,0,42.175241,31296.452351,0.0,31296.452351,...,1.454319,0.0,0.0,2.423864,15.512732,4489.481640,0.969546,52.840244,3.393410,152.703457
HG00101.1.MI_120104_4,1,0,0,0,0,0,48.312524,33184.906523,0.0,33184.906523,...,0.966250,0.0,0.0,2.898751,7.730004,5064.118772,0.966250,59.907530,1.932501,57.008778

In [4]:
Ydata.head()

id
HG00096.1.MI_120104_4    2
HG00097.7.MI_120224_2    2
HG00099.5.MI_120327_3    2
HG00100.2.MI_120126_4    2
HG00101.1.MI_120104_4    2
Name: population, dtype: int64

In [5]:
classifier_config_dict['sklearn.feature_selection.SelectPercentile'] = {
    'percentile': range(1, 10),
    'score_func': {
        'sklearn.feature_selection.f_classif': None
    }
}

classifier_config_dict['tpot.builtins.resAdjTransformer'] = {
    'C': [['lab1','lab2','lab3','lab4','lab5','lab6']],
    'adj_list': ['testingData/adj_list.csv']
    
}

In [6]:
seed=42
n_gen = 5
n_pop = 10


Xtrain, Xtest, Ytrain, Ytest = train_test_split(Xdata, 
                                                Ydata, 
                                                random_state=42+int(), 
                                                train_size=0.75, 
                                                test_size=0.25, 
                                                stratify=Ydata)

In [7]:
Xtrain.head()

,lab1,lab2,lab3,lab4,lab5,lab6,hsa-let-7a-1-3p,hsa-let-7a-1-5p,hsa-let-7a-2-3p,hsa-let-7a-2-5p,...,hsa-miR-95-3p,hsa-miR-95-5p,hsa-miR-96-3p,hsa-miR-96-5p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
id,,,,,,,,,,,,,,,,,,,,,
HG00321.2.MI_120126_5,0,1,0,0,0,0,53.446243,39017.093890,0.0,39017.093890,...,0.890771,0.0,0.0,2.226927,23.160039,5269.354221,0.890771,16.924644,0.000000,89.077072
HG00114.6.MI_120217_1,0,0,0,0,0,1,62.643482,44041.281569,0.0,44041.281569,...,1.456825,0.0,0.0,4.370475,10.197776,7374.448986,1.456825,45.161580,2.913650,104.891412
NA11830.3.MI_120120_3,0,0,1,0,0,0,87.906119,43142.608024,0.0,43142.608024,...,0.000000,0.0,0.0,2.144052,19.296465,8541.901917,4.288103,141.507411,0.000000,51.457240
HG01790.3.MI_120120_5,0,0,1,0,0,0,28.939090,43652.391440,0.0,43652.391440,...,1.113042,0.0,0.0,3.895647,13.913024,2503.231300,0.000000,25.043443,4.452168,359.512543
NA12400.2.MI_120126_6,0,1,0,0,0,0,70.110646,55949.283341,0.0,55949.283341,...,0.987474,0.0,0.0,1.974948,14.812108,5611.814138,7.899791,182.682670,0.493737,155.033401

In [ ]:
tpot = TPOTClassifier(generations=n_gen, population_size=n_pop, 
                      verbosity=2, cv=5, config_dict=classifier_config_dict,
                      scoring='balanced_accuracy', random_state=42 + int(seed),
                      template="resAdjTransformer-Selector-Transformer-Classifier")
tpot.fit(Xtrain, Ytrain)

Imputing missing values in feature set

HBox(children=(FloatProgress(value=0.0, description='Optimization Progress', max=60.0, style=ProgressStyle(desâ€¦

In [ ]:
tpot._imputed